---
- name: Update Ubuntu Focal and set up MySQL master
  hosts: all
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Install PyMySQL
      apt:
        name: python3-pymysql
        state: present

    - name: Ensure MySQL service is running and enabled
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Configure MySQL for replication
      copy:
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
        content: |
          [mysqld]
          bind-address            = 0.0.0.0
          server-id               = 1
          log_bin                 = /var/log/mysql/mysql-bin.log
          log_bin_index           = /var/log/mysql/mysql-bin.index
          binlog-format           = ROW
          innodb-flush-log-at-trx-commit  = 1
          sync-binlog             = 1
          binlog-ignore-db        = mysql
          binlog-ignore-db        = information_schema
          binlog-ignore-db        = performance_schema
          binlog-ignore-db        = sys

    - name: Restart MySQL to apply changes
      service:
        name: mysql
        state: restarted

    - name: Set MySQL root password
      mysql_user:
        login_user: root
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: root
        password: password
        host: '%'
        priv: '*.*:ALL,GRANT'
        state: present
  
    - name: Remove root@localhost user
      mysql_user:
        login_user: root
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: root
        host: localhost
        state: absent

    - name: Create replication user
      mysql_user:
        login_user: root
        login_password: password
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: repl_user
        password: repl_password
        priv: '*.*:REPLICATION SLAVE'
        host: '%'
        state: present

    - name: Restore database
      mysql_db:
        login_user: root
        login_password: password
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: testdb
        state: import
        target: /vagrant/testdb.sql
        force: true