---
- name: Update Ubuntu Bionic and set up MySQL master
  hosts: all
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Install PyMySQL
      apt:
        name: python3-pymysql
        state: present

    - name: Ensure MySQL service is running and enabled
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Configure MySQL for replication
      copy:
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
        content: |
          [mysqld]
          bind-address            = 0.0.0.0
          server-id               = "{{ worker_id | int + 1 }}"
          relay-log               = /var/log/mysql/relay-mysql.log
          relay-log-index         = /var/log/mysql/relay-log.index
          skip-slave-start

    - name: Restart MySQL to apply changes
      service:
        name: mysql
        state: restarted
        
    - name: Set MySQL root password
      mysql_user:
        login_user: root
        login_host: localhost
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: root
        password: password
        host: '%'
        priv: '*.*:ALL,GRANT'
        state: present

    - name: Remove root@localhost user
      mysql_user:
        login_user: root
        login_host: localhost
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: root
        host: localhost
        state: absent

    - name: Create replication user
      mysql_user:
        login_user: root
        login_host: localhost
        login_password: password
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: repl_user
        password: repl_password
        priv: '*.*:REPLICATION SLAVE'
        host: '%'
        state: present
  
    - name: Get master status
      command: mysql -u root -ppassword -h 10.0.0.16 -e "SHOW MASTER STATUS\G"
      register: master_status

    - name: Configure replication on slave
      mysql_replication:
        mode: changemaster
        login_password: password
        login_unix_socket: /var/run/mysqld/mysqld.sock
        master_host: 10.0.0.16
        master_user: repl_user
        master_password: repl_password
        master_log_file: "{{ master_status.stdout | regex_search('File: (.*)', '\\1') | first }}"
        master_log_pos: "{{ master_status.stdout | regex_search('Position: (.*)', '\\1') | first }}"

    - name: Start mysql replica thread
      community.mysql.mysql_replication:
        mode: startslave
        login_password: password
        login_unix_socket: /run/mysqld/mysqld.sock

    - name: Restore database
      mysql_db:
        login_user: root
        login_password: password
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: testdb
        state: import
        target: /vagrant/testdb.sql
        force: true

    - name: Check replica status
      community.mysql.mysql_replication:
        mode: getslave
        login_password: password
        login_unix_socket: /run/mysqld/mysqld.sock
      register: worker_status

    - debug:
        var: worker_status
